### ISSUE TITLE
MacOS 10.8.5 cannot connect

### ISSUE THREAD

**Issue by chriscoxadobe** [evil-mad/robopaint-rt#15]
MacOS 10.8.5 on a MacBook Pro and MacBook Air -- watercolorbot is not detected, and always runs in demo mode.

But RobotPaint can detect and use the same bot, on the same systems.
I've tried Apple's latest JRE 6, and downloaded JRE 7 - no change in the problem.

**Comment by oskay** [comment]
I'm sorry to hear about the trouble.  

I can say that RoboPaint RT was written (and initially tested) on a MacBook Pro running 10.8.5, so there is not a universal problem with this configuration; something else must be different on your system.  That could be, for example, other USB devices on your system (or possibly certain software that talks to your serial ports).

One (obvious) thing to check: Make sure that RoboPaint is _not_ running when you open RoboPaint RT.

Is there a chance that you might consider trying to run RoboPaint RT from source on your computer? You would need to download and install Processing 2.0.3.  (It can display debug information, including a list of the serial ports that it finds.)  Otherwise, I can package up a custom version of RoboPaint RT for you to try, that lists the serial ports that it finds.

**Comment by chriscoxadobe** [comment]
The only other USB devices are built into the laptops, and the only other USB driver is a wacom tablet driver.
No serial device drivers or applications.
No other applications running when I launch RobotPaintRT.

The system recognizes the EiBotBoard  (as does RoboPaint):
  Product ID:   0xfd92
  Vendor ID:    0x04d8  (Microchip Technology Inc.)
  Version:   1.82
  Speed:    Up to 12 Mb/sec
  Manufacturer: SchmalzHaus
  Location ID:  0x14100000 / 8
  Current Available (mA):   500
  Current Required (mA):    100

I'll download processing and give the RoboyPaintRT source a try.

**Comment by oskay** [comment]
Thank you.

When you do run form within Processing, please look at the text output in the "console," which should print out some debugging information:

I found _n_ serial ports, which are:
[0] "/dev/tty.Bluetooth-Serial-1"
[...]
Now entering offline simulation mode.

**Comment by chriscoxadobe** [comment]
I downloaded Processing, Ani, and the Robopaint RT sources.
When running within Processing, it recognizes the Eibotboard and works just fine.Console says:
  Serial port /dev/tty.usbmodem1411 confirmed to have EBB.
  Now entering interactive painting mode.

But your packaged version 1.1 (Nov 15, 2013) does not recognize the board.

**Comment by oskay** [comment]
Thank you running those tests and for the detailed report.  

(And-- wow --I'm quite surprised by what you found.)

If you select "Export Application" from the file menu, to create your own executable, does that work?

**Comment by chriscoxadobe** [comment]
So far exporting doesn't create a runnable app - but I've just been looking at the libraries, and it seems that processing has had a few updates since the build that you were using.   The file layout is different, and several of the libraries have changed size (I haven't done a complete diff yet).

**Comment by oskay** [comment]
We're currently using Processing 2.0.3 for our exported versions, after finding a problem with Windows exports in 2.1.  IIRC, we did not have any Mac-side issues running in, or exporting from, 2.1.

**Comment by chriscoxadobe** [comment]
BTW - I'm in san jose.  Worst case I could meet you at the EvilMadScientist Shop and work on this.

**Comment by chriscoxadobe** [comment]
I've got processing 2.1 (latest on their download page).

**Comment by oskay** [comment]
> Worst case I could meet you at the EvilMadScientist Shop and work on this.

Quite possibly, but I need to do a little research first.   (I am _very_ glad that you at least have a way to run the program for now, if a little less elegant. I'm not sure how many other people are having this issue.)

**Comment by chriscoxadobe** [comment]
Out of curiosity I tried another machine with MacOS 10.7.5 (thinking maybe Apple's java changes in 10.8.x caused the problem), and got the same result - RobotPaint works, RT fails to see the board.

**Comment by oskay** [comment]
So far, we haven't had any other reports of this case, so I can't help but wonder if there's something different about how you're operating your machines. 

I'll see if I can't put together a debug version of a packaged program for you to run, see if we can't get to the bottom of this.  Thanks again!

**Comment by chriscoxadobe** [comment]
One of the machines is kind of dirty with a lot of apps, but the air is clean except for a wacom tablet driver.
I've tried alternate computers, alternate cables, even an alternate power supply (I have too many around here…).
The only other common factor would be the eibotboard.

**Comment by chriscoxadobe** [comment]
I also tried removing the wacom driver and rebooting - same result.

**Comment by chriscoxadobe** [comment]
I downloaded Processing 2.0.3 and ran the RobotPaintRT source - it fails to detect the board:

I found 10 serial ports, which are:
[0] "/dev/tty.Bluetooth-Serial-1"
[1] "/dev/cu.Bluetooth-Serial-1"
[2] "/dev/tty.Bluetooth-Serial-2"
[3] "/dev/cu.Bluetooth-Serial-2"
[4] "/dev/tty.Bluetooth-Modem"
[5] "/dev/cu.Bluetooth-Modem"
[6] "/dev/tty.Bluetooth-PDA-Sync"
[7] "/dev/cu.Bluetooth-PDA-Sync"
[8] "/dev/tty.usbmodem1411"
[9] "/dev/cu.usbmodem1411"
To use the serial library, first open
Serial port /dev/tty.usbmodem1411 could not be activated.
Now entering offline simulation mode.

Applications -> Utilities -> Terminal.app
and enter the following:
sudo mkdir -p /var/lock
sudo chmod 777 /var/lock

---

So the problem appears to be in Processing 2.0.3 on MacOS, where it is fixed in Processing 2.1.
2,0.3 does create a runnable app package (which still can't find the board),  but 2.1 seems to have some differences and the exported app doesn't launch correctly.

**Comment by oskay** [comment]
A permissions issue was at the top of my list; I'm sorry that I didn't have time to follow up further yesterday.  I'll see if I can make this work in 2.1 next.

**Comment by oskay** [comment]
It may be better to actually just build an installer that runs a script to fix the serial port permissions.

**Comment by oskay** [comment]
There is apparently a bug in 2.1 that is preventing exported applications from working on Mac in many circumstances.  Coming up against it now, I now remember finding this same one a month ago.   (My apology; when I said "IIRC, we did not have any Mac-side issues running in, or exporting from, 2.1," I was apparently _not_ recalling correctly.)

Reference:
http://forum.processing.org/two/discussion/comment/2239
https://github.com/processing/processing/issues/2181
There are some possible workarounds, but I'll work on the installer approach instead, because

**Comment by oskay** [comment]
I've uploaded an installer, as part of the latest release, that may solve the issue for you:  RoboPaint.RT.Installer.dmg

Would you please give that a try and let me know how it goes?

**Comment by chriscoxadobe** [comment]
I ran the installer, and the result is the same as before - bot not found, running in simulation mode.

Update - on the third and fourth launch it connected.
Could there be a timing problem with the port initialization?

Further, after RobotPaint has used the port, RT wont't connect for the first 20 seconds or so after robopaint exits.  After that, it works.

**Comment by oskay** [comment]
I'm sorry for the slow follow-up here; we've been awfully busy shipping robots!

And, I didn't see your update until just now.  All previous signs pointed towards some kind of "port locking" type problem, and your latest results would point to that as well. However, I have also been working on the other approach.

I've packaged up an experimental version of RoboPaint RT for you to try, exported from a patched fork of Processing 2.1:

http://evilmadscientist.s3.amazonaws.com/scratch/RoboPaint%20RT.app.zip

**Comment by tricianguyen** [comment]
Hi - I am having tremendous trouble getting my MacBookPro running 10.7.5 to recognize the watercolor bot USB as well.  I wrote a separate email but am updating the problem here too.  Have done the standard rebooting, trying different cables, downloaded newest JAVA this morning before RoboPaint RT.  Then finally tried RoboPaint in two versions for Mac and they both got stuck in opening mode.  Never opened.  

I have downloaded the .zip thing above and for the first time the mac is now driving the watercolorbot.  You had better put that as the download software ASAP because there are tons of people starting to put your bots together who are going to get majorly frustrated.  My kids gave up after spending a day putting it together.  They are FLL champs and have put their own 3-D printer together so they aren't newbees and were pretty disappointed when they couldn't get the software to work.  So they put it back into the box and on the shelf.  I was determined to get it to talk as I want them to hack it.

**Comment by oskay** [comment]
Hi Patricia,
Thank you for the report-- This is all very, very helpful information:
- That you've encountered the issue on 10.7.5 (That is our first report of it happening on 10.7.5.)
- That there is an issue with RoboPaint not opening on the Mac (that we have also not been able to reproduce).  I'm opening a separate bug report about that, and we may ask you for additional details.
- That the "patched fork version" is working for you.   I posted that six days ago, and neither of the other two people who have reported this issue have gotten back to us whether or not it helped.  (It works for us here, but so did the original release version....)  I'll be updating our release with the patched version shortly.

**Comment by tricianguyen** [comment]
We were not clear here on which Robopaint to download - one reads:

Robopaint-Mac-0.7.0.dmg   --Is that 10.7.0 version and the '1' is missing? Is that for later versions?
Robopaint-Mac 10.6-v.0.7.0.dmg  -- Is that versions 10.6.0 up to 10.7.0?  Again the '1' is missing?  

So would it be the first one we would need for 10.7.5?  Both froze and will try again now.

**Comment by oskay** [comment]
The RoboPaint version is 0.7.0.  One version is for Mac 10.6, and the other is for MacOS versions 10.6.x through 10.9.x.  There is no "1" missing, but I had not recognized that the version number could be confusing in that way. 

For your computer (on 10.7.5), please use Robopaint-Mac-0.7.0.dmg.  I'd suggest waiting 30 seconds after quitting RoboPaint RT before launching it, and allow a minute or two at first launch, just in case it will start (but slowly).  I'm very, very sorry for the continued trouble, and I do thank you again for the bug reports and your testing.

**Comment by oskay** [comment]
I have updated the current release with the version of RoboPaint RT exported from the patched version of Processing 2.1.  (To be clear, there are no changes to the RoboPaint RT source code, just to the version of Processing.)

The new version is called RoboPaint.RT.Mac-20140101.zip, and it's attached to the release, here:
https://github.com/evil-mad/robopaint-rt/releases/tag/v1.1

I am marking this issue as closed.  We'll be following up with the RoboPaint issue separately, over here: https://github.com/evil-mad/robopaint/issues/126

**Comment by orenjacob** [comment]
Hi. Just got my WaterColorBot unpacked and built with my daughter Toby.  Fantastic experience.
Plugged it into my Mac and RT wouldn't recognize it at all.
RoboPaint did recognize it, and we put together a simple image to print, and the printer came alive and started moving.
But the pen (servo) doesn't seem to ever go up or down.  When pushing the servo up/down by hand, it seems pretty stiff.  But it can move the up/down travel I would expect it to to get the brush in contact with water/paint/etc... but it doesn't do that when I sent it direct commands (Brush Up/Brush Down) or while trying to paint an image.

So I think I might have 2 problems - the "can't recognize the WaterColorBot in RT on a Mac" problem, and my brush up/down servo doesn't seem to respond at all.

Any thoughts about how best to proceed?

**Comment by oskay** [comment]
@orenjacob I see that you posted this to our forums as well.  It would be helpful if you would pick one place so that we do not have to have the same conversation twice.  This issue report is specifically about RoboPaint RT, so I'll respond to this one here.

Can you please say which version of RoboPaint RT you are using?  Are you certain that it is the "RoboPaint.RT.Mac-20140101.zip" version?  And, which OS version are you on?

**Comment by orenjacob** [comment]
Thanks for your prompt response, appreciate it. 

Robopaint reports 27.01430.0(1430.0) in the about dialog. 
RobopaintRT just says 1.0. 

My Mac (MacBook air vintage Sumer '11 - no AirPlay) is running 10.9.1. 

Looking at the .dmg file, it looks like 0.7.0.  

 I don't see a .zip file still on my Mac. 

Side note: the pen up/down issue isn't in RT only, but happens in both RT and RoboPaint. 

Is there any other info I can send you to be helpful?

Oren

**Comment by oskay** [comment]
@orenjacob 
Please download a new copy of the file from our releases page, and make sure that it is the "RoboPaint.RT.Mac-20140101.zip" version.  We released this re-packaged version this week, to address this issue.  It would be very helpful to know if it does or does not fix the issue for you.

The servo issue is a hardware problem, not related to this. I followed up in your post on our forum about it.

**Comment by orenjacob** [comment]
OK, will try that this evening.
Thanks Windell.
Oren

**Comment by orenjacob** [comment]
Hi.
Tried the build you recommended, and I can now control the WaterColorBot in real time with RobotPaintRT.
Thanks for the email back.

Now, I have the additional problem that our servo doesn’t go up/down, so I can’t do brush-up or brush-down commands.  It appears to just not respond to those commands.

Any thoughts about how to fix our brush servo issue?

Thanks again,
Oren

**Comment by orenjacob** [comment]
And one additional challenge.. is seems like every time its doing a brush wash move, when it goes from water container 1 to 2 to 3… when it’s doing the back and forth in 3 only, the Y axis (2) motor seems to skip (sounds a little like its “crunching”) and the brush gets misaligned.
I can tell this because when it returns home later, it crashes into the top bumper and realigns itself.
However, if I give it commands to go to the 4 corners in successions and back to home without a color change, things seem to work fine.
Have you noticed any kind of motor skipping in the command sequence to clean brushes ever happening?

**Comment by oskay** [comment]
@orenjacob 
Glad to hear that the fix worked.

The other issues that you are are bringing up are _not relevant_ to this MacOS/RoboPaint RT issue, which is already closed, and for which the other participants in this thread do not need to be receiving e-mail notification.  I would be happy to help you with them but _this is not an appropriate venue._  

_As I already indicated_ I have followed up in our regular support forums about the servo issue.

**Comment by orenjacob** [comment]
To all,

Apparently I have been emailing github, and therefore a bunch of you, with my past replies to this thread.
Sincere apologies, the way this email (and previous ones on this thread) were presenting to me in my email clients made that totally opaque to me, and only after the strongly emphasized email below did I go sleuthing through some headers to figure out that.  I had thought I was replying to Windell directly.

Sorry everyone. I’m shutting up on this thread now. Sincere apologies, I had no idea I was emailing all of you.

**Comment by chriscoxadobe** [comment]
Sorry for the delay - work and holidays kept me away from the toys at home.

But the good news is that the 1/1/2014 release seems to have completely solved the connection problems.
